### PR TITLE
Overhaul input pipeline, use Tensorboard

### PR DESCRIPTION
**Pull request by V-Xing**
Following our discussion in the Google group, this is my version of the bls2017 example. I mainly tweaked the input pipeline to use a clean Dataset+Re-initializable Iterator structure and added Tensorboard visualization.
Any feedback is welcome!
The main changes are documented in the commit message.

### CODE REVIEW

**Comment by jonycgn** [comment]
Hey Victor,

thanks a bunch for this!

However, before we can accept the pull request, we need to reapply the Google/TensorFlow style guide (https://www.tensorflow.org/community/style_guide). Generally, that includes 2 spaces, comments in descriptive (not imperative) form, certain __future__ imports, among other things.

If you keep the changes from the original file to the minimum necessary to implement the functionality, I think that should cover most of it. This would also make it easier to review the changes, because the diff would be much shorter! Would you have time to do that?

Thanks,
Johannes

**Comment by jonycgn** [comment]
Also, we should keep a list of contributors somewhere. In the mean time, I'll try to figure out how best to do that.

**Comment by V-Xing** [comment]
Sure, I'll take some time to do that soon!

**Comment by V-Xing** [comment]
Hey,
My latest commit hopefully follows the TF style guide. I kept differences to the original file to a minimum to implement the features described in the commit message.
Any feedback is welcome!

There are also a few features I implemented in my own version of the code which I did not include in this commit for the sake of simplicity:

- As I have needed to compress a bunch of images at once, and calling the compress and decompress functions separately is very slow because each call initializes a new graph, I have a function that loops over multiple files to do compression+decompression. It is basically the compress() and decompress() functions merged together so it is simple to write by yourself.

- I use a numbering system to identify my training runs and to keep my Tensorboard log directory organized. My TB log dir contains a subdir for each run (run1/, run2/...) that contains the summaries for Tensorboard plots corresponding to that run. I actually provide the run number as an argument of the script (python bls2017.py train 1 ...) and it automatically creates the right checkpoint and log subdirectories.

**Comment by jonycgn** [comment]
Hey,

I ended up cherry picking only some of your changes: the input pipeline for training, creating summaries for Tensorboard, and computing PSNR and MS-SSIM.

Although it is clearly useful, I don't want to include the code to do validation/test at this point. There are two reasons for that:
- First, the example model is meant to be "educational", so that it would be counterproductive to add a lot of complexity. The logic you've implemented is fairly complex, and I'm trying to keep it to a level where it's relatively easy to understand what's going on.
- The other reason is that we're expecting some fundamental changes in how models are set up in the new major release of TensorFlow. Here, we've relied on `MonitoredTrainingSession` to abstract some of the underlying logic, but there are likely going to be new patterns to do this in TF 2.0. Until we know exactly what this will look like, I'd like to stick to the existing code, and then switch to newer patterns when the time comes, to keep the code simple. I will revisit your code then to see what the simplest way is to incorporate the functionality you've implemented.

Note that I also passed on the data augmentation code for now, because I want the model to be fairly close to the original paper. It may be really useful for some applications, but augmentation has the potential of changing the statistics of the training data, so I'd rather not have that be the default for an example model.

Again, thanks for your contribution!

**Pull request closed without merging**
